# Generated by Django 3.1.5 on 2021-02-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profiles',
        ),
    ]
