# Generated by Django 3.1.5 on 2021-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210228_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='password',
            field=models.CharField(default='12345', max_length=15),
        ),
    ]
