# Generated by Django 3.1.5 on 2021-03-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='password',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
